Financial-Times/o-typography

main.scss, scss/_mixins.scss, scss/_variables.scss, scss/deprecated/_functions.scss, scss/deprecated/_index.scss, scss/deprecated/_mixins.scss, scss/deprecated/_variables.scss
/ping @jamesnicholls @Thurst-ft In the next major version of o-ft-typography (which will be renamed o-typography), you’ll need to include font-face declarations yourselves, using o-fonts or your own webfont loader.
=> Font-face declaration deprecation warning

.travis.yml, demos/badges.html, demos/body.html, demos/headings.html, demos/labels.html, demos/leads.html, demos/metadata.html, demos/titles.html, main.scss, scss/_body_article.scss, scss/_leads.scss, scss/_mixins.scss, scss/_titles.scss, scss/_variables.scss, scss/deprecated/_mixins.scss, scss/deprecated/_wrapped.scss
- Fix linting errors with latest version of scss-lint
- Fix a syntax error in Sass 3.4 (`unquote()` won't accept an empty list as an argument anymore)
- Remove Times New Roman from front families
- Add a parameter to avoid outputting any `@font-face` declarations /cc @Thurst-ft @jamesnicholls
=> Prepare for @font face declarations removal

main.scss
The module would grow too big if we follow the normal deprecation path, where o-typography and o-ft-typography classes would cohabit, so I propose we simply prompt users to update to a newer version.
(the low adoption rate makes it okay IMHO)
=> Prompt users to update o-typography to a newer version

scss/_helpers.scss, scss/_variables.scss
$o-fonts-families is defined in _variables.scss and therefore overwrites the $o-fonts-families definition in o-fonts. We shouldn't be overwriting this in o-typography.
This PR:
- deletes the redefinition of $o-fonts-families so fonts available will be those defined in o-fonts
- adds in appropriate namespacing for $font-scale, but renaming it $o-typography-font-scale
=> Add bold by fixing bug

README.md, main.scss, scss/_helpers.scss, scss/_progressive-font.scss, scss/_type_matrix.scss, scss/_variables.scss
A major annoyance with webfonts is the FOIT while the font is loading.
This adds functionality of depending on a certain class existing further up the dom (e.g. on the `html`) before setting the font on an element. Coupled with some sort of `FontFaceObserver` pattern (i.e. only add the class once the font is loaded), this will eliminate the FOIT
Also does some scaling of the size of the fallback font to match the webfont
e.g.
```
.foo {
@include oTypographySerifDisplay(m, $load-progressively: true);
}
```
=>
```
.foo {
font-family: serif;
font-size: 18px;
line-height: 24px;
font-weight: 400;
}
.loaded-SerifDisplay .foo {
font-family: FinancierDisplayWeb,serif;
font-size: 20px;
}
```
```
.foo {
@include oTypographySerifDisplaySize(m, $with-progressive-size: true);
}
```
=>
```
.foo { …
```
=> Progressive font functionality

README.md, demos/src/article.mustache, demos/src/asides.mustache, demos/src/body-wrapper.mustache, demos/src/body.mustache, demos/src/headings.mustache, main.scss, origami.json, scss/_body_aside.scss, scss/_body_common.scss, scss/_body_general.scss, scss/_color_use_cases.scss, scss/_headings.scss, scss/_type_matrix.scss, scss/_wrapped_aside.scss, scss/_wrapped_general.scss
OK. Ready to re-merge this and create o-typography v4.
I've also changed the aside text to match the body which is what it is in this article: https://next.ft.com/content/94e97eee-ce9a-11e5-831d-09f7778e7377
And I've replaced metric light with metric regular.
=> Revert 70 revert 67 migrate from n content body

README.md
Since #71 Metric Light isn't used any more.
Something to consider for v5 (maybe you've talked about this before, I dunno): now Sans is regular, does there need to be the distinction between Sans and SansData? Looks a little weird to have two identical fonts with different sizings.
=> Update font matrix table to reflect current weights

README.md
Sorry for the difficult-to-read diff. The change is `oTypographyFontSize ` -> `_oTypographyFontSize` (added underscore)
=> Fix the name of replacement font-size mixin in README

README.md
(Change: `_oTypographyFontSize` -> `oTypographySize`)
Sorry team, my last fix was erroneous. Looking into the code, it seems the equivalent of the [old `font-size` mixin](https://github.com/Financial-Times/o-typography/blob/v4.3.4/scss/_helpers.scss#L55) would be the [`oTypographySize`](https://github.com/Financial-Times/o-typography/blob/master/src/scss/_mixins.scss#L53) mixin, since it handles line-heights too.
I regret the error 🌹
=> Fix mixin name in README (again… oops)

src/js/typography.js, test/typography.test.js
To wait for fonts to load the consumer must call `loadFonts()`, which is already called internally. this PR avoids doing the work twice if loadFonts has already executed once
=> avoid double className manipulation

README.md
Is this correct?
Is this necessary?
x
=> Add a V5-removed mixin to the migration guide

README.md, bower.json, demos/src/custom-links.mustache, demos/src/demo.scss, origami.json, src/scss/use-cases/_general.scss
This includes the `oTypographyLinkCustom` mixin, which allows you to
create links with custom colors. You can only used valid o-colors
palette colors with these.
The `oTypographyLink` mixin also uses the custom links mixin.
This resolves #119
=> Add the ability to generate custom links

demos/src/headings.mustache, package-lock.json, src/scss/use-cases/_headings.scss
I'm slowly beginning the process of using o-typography styles for all our article elements.
Starting with the headlines - currently the origami headlines aren't responsive, so bringing these in line with the sizes used on FT.com.
The large headline at 56px ($scale: 8) was too large (it's currently 52px on FT.com), so bringing that down to 7 (48px) on XL.
=> Make headlines responsive

src/scss/use-cases/_headings.scss
The motivation came whilst upgrading o-typography in the web-app.
The heading used to be huge:
But now it's responsive it's maybe a bit small:
So we can bump it up a little:
Confirmed with @pixie-ofuono and @adgad.
=> Increase headline size on tablet.

README.md, demos/src/product-headings.mustache, main.scss, origami.json, src/scss/_color-use-cases.scss, src/scss/_mixins.scss, src/scss/use-cases/_headings.scss, src/scss/use-cases/_product-headings.scss, src/scss/use-cases/_wrapper.scss
This PR adds the changes requested by James, #133 and looks like this:
@notlee I think we may need to consider branding for oTypography for this kind of thing, but in the future so that this is not a breaking change. 
Closes #133
=> add product heading styles

README.md, bower.json, demos/src/custom-links.mustache, main.scss, src/scss/use-cases/_general.scss
- @draysonandstock preference was that the link text isn't allowed to partly wrap to another line
=> Add external link class / mixin

main.scss
This style (from @draysonandstock inc) is used across more than one app so it made sense to extract it. (eg. consent forms, myFT)
Eg Product announcements header:
=> Add variant of product heading level 7 with thin border

src/scss/use-cases/_general.scss
Follow-up to https://github.com/Financial-Times/o-typography/pull/139
=> External link class - set right margin to accomodate icon

bower.json
This [is documented](https://github.com/Financial-Times/o-typography#progressive-loading-web-fonts) but not currently possible as OBT does not find and build the JS.
=> Support progressive font loading via the build service.

src/js/typography.js, test/typography.test.js
This updates `display` labels to match those used in the css https://github.com/Financial-Times/o-typography/blob/master/src/scss/_type-mixins.scss#L36
It looks like its been this way for a while: https://github.com/Financial-Times/o-typography/commit/cd7bb58f07676e0c64d71adf771847610e527390#diff-cc5f92b397da4aef0ff4fed64a71a7a4L410
o-typography logic is duplicated in n-ui. Will submit a separate PR there.
https://github.com/Financial-Times/n-ui/blob/b08b20bf757bab1103f09adfecb22a90feebca36/browser/layout/partials/enhance-fonts.html#L3
Before (core)
After (core)
=> Fix progressive loading of the display font.

src/scss/_type-mixins.scss
It appears this was intended for v5 but omitted by mistake.
https://github.com/Financial-Times/o-typography/blob/master/migrating-v4-v5.md
=> Add `oTypographySerifItalic`.

src/scss/use-cases/_general.scss
Now scales according to list font size. E.g. a small metric font:
Updates the bullet position, aligning centre within the line height (.gif: waitttt forrrrr itttt):
=> Make bullet sizes relative

src/scss/use-cases/_general.scss
Before:
After:
Space either side of the icon has been tightened in the process. Thoughts?:
Before/After
=> Enable external links to wrap.

src/scss/use-cases/_general.scss
Align external link icon correctly regardless of line height, border width, or font size.
Before (with made up typography sizes)
After (with made up typography size)
=> Improve external link alignment.

demos/src/custom-links.mustache, src/scss/use-cases/_general.scss
Icon size/position is now correct in IE, including IE9.
New mixin can be used to output the external link icon in other contexts, e.g:
=> Improve external link in IE. Break out external link mixin for icon / icon position.

src/scss/use-cases/_general.scss
- ensure hidden text is left-aligned in case parent link has text-align: right
- use transparent text
=> External link styling

src/scss/use-cases/_general.scss
Related issue and discussion: https://github.com/Financial-Times/o-typography/issues/160
This prevents the external link icon from wrapping onto a newline on its own, whilst still allowing the copy of the link to wrap.
IE9-11 have issues rendering SVG backgrounds at the correct size and aspect ratio. To work around these issues I have used `@supports` to provide a pseudo element based fallback, which will exhibit the current behaviour of allowing the icon to wrap on its own.
=> Prevent external link icon from wrapping on its own.

src/scss/use-cases/_general.scss
Whitelabel demos are failing as `o-typography` has not been branded. This is a quick fix to allow `o-typography` to build. 
In addition, it updates the link mixin to use an `o-colors` usecase for the hover state. **Must not be merged before the [color usecase is correct](https://github.com/Financial-Times/o-colors/pull/166).**
=> Fix whitelabel build before branding more completely.

src/scss/_mixins.scss
`oTypographySetCustomFont` has a `$family` argument, so it makes sense to have the same argument name for `oTypographyDefineFontScale` (although a font or font family is allowed).
=> Update oTypographyDefineFontScale param from "font" to "family".

README.md, src/scss/_brand.scss, src/scss/_functions.scss, src/scss/_mixins.scss, src/scss/_variables.scss, src/scss/use-cases/_general.scss, src/scss/use-cases/_headings.scss, test/scss/_mixins.test.scss
We decided for the v5.8.0 release **not** to use a custom font like:
```scss
// Use Roboto for the sans font.
$roboto-family: 'Roboto, sans-serif';
@include oTypographySetCustomFont(
$family-style: 'sans',
$family: $roboto-family,
$variants: (
(weight: regular, style: normal),
(weight: semibold, style: normal),
(weight: bold, style: normal)
)
);
// Define a custom font scale for Roboto.
@include oTypographyDefineFontScale(
$family: $roboto-family,
$scale: (
-2: (12, (12 * 1.3)),
-1: (14, (14 * 1.3)),
0: (16, (16 * 1.3)),
1: (18, (18 * 1.3)),
2: (20, (20 * 1.3)),
3: (24, (24 * 1.3)),
4: (28, (28 * 1.3)),
5: (32, (32 * 1.3)),
6: (40, (40 * 1.3)),
7: (48, (48 * 1.3)),
8: (56, (56 * 1.3)),
9: (72, (72 * 1.3)),
10: (84, (84 * 1.3))
));
```
And **instead** to:
```scss
// Add Roboto font. …
```
=> Do not register custom font via o-typography.

README.md, src/scss/_mixins.scss, test/scss/_mixins.test.scss
Custom line heights in responsive typography is not output. E.g this is effecting the topper, which is a :
```scss
@include oTypographySize($scale: (default: (-1, 22px), L: (0, 24px)));
```
https://github.com/Financial-Times/o-teaser/blob/master/src/scss/elements/_related-items.scss#L15
=> Fix custom line heights for "oTypographySize".

src/scss/_brand.scss
For users who are using the font family variables directly, e.g. `font-family: $o-typography-serif`.
=> Correctly font family variables.

src/scss/use-cases/_general.scss, test/scss/_mixins.test.scss
The `$color` argument is currently ignored.
=> Fix custom external link icon colour.

README.md, src/scss/_brand.scss, src/scss/use-cases/_general.scss, src/scss/use-cases/_headings.scss
Adds support for changing header and body scales, and the blockquote colour.
Also snuck in a little change to `sub`/`sup`, so they use relative font units if relative font units are enabled.
=> Support whitelabel brand customisation.

src/scss/_brand.scss, src/scss/_functions.scss, src/scss/_mixins.scss, src/scss/_type-mixins.scss, test/scss/_mixins.test.scss
**background**
We have mixins such as `oTypographyBold('sans')` and `oTypographySansBold()`
to output the correct `font-weight` for strong copy. These mixins are useful as some 
fonts may only support "semibold" or "bold" weights, and we don't want to 
accidentally mix and match font-weights. However these mixins were created 
before branding and these weights were not customisable.
**new feature**
This PR makes "bold" font weights customisable by adding a 'bold-weight' brand 
variable. It may be set to "bold" or "semibold" according to the fonts a brand is 
using. Variants of the font type 'sans', 'serif', 'display' may be used to modify the
font weight for a font type within a brand (see the master brand brand config as 
an example).
```scss
@include oTypographyCustomize(( …
```
=> Make the default "sans", "serif", or "display" bold font weight customisable

src/scss/use-cases/_general.scss
And nested ordered lists.
As reported in `#ft-origami`:
=> Allow an un-ordered list within an ordered list.

src/scss/_functions.scss, test/scss/_mixins.test.scss
E.g. `@include oTypographySize($scale: -1, $line-height: unset);`
should set a line height of 'unset', without trying to convert
'unset' to rems (and erroring).
Relates to: https://github.com/Financial-Times/o-forms/pull/261#pullrequestreview-233463697
=> Handle non-numeric values when relative units are enabled.

src/scss/_brand.scss
See https://github.com/Financial-Times/o-normalise/pull/39
=> Update the default focus colour of custom links to improve contrast.

README.md, bower.json, main.scss, src/scss/_deprecated.scss, src/scss/_functions.scss, src/scss/_mixins.scss, src/scss/_variables.scss, src/scss/use-cases/_article.scss, src/scss/use-cases/_asides.scss, src/scss/use-cases/_general.scss, src/scss/use-cases/_headings.scss
This deprecates:
- oTypographyMargin
- oTypographyPadding
- oTypographySpacingSize
This is not considered a breaking change as o-spacing
is a new component.
See the [o-spacing proposal](https://github.com/Financial-Times/origami-proposals/issues/10).
=> Introduce o-spacing.

MIGRATION.md, README.md, main.scss, origami.json, src/js/typography.js, src/scss/_brand.scss, src/scss/_functions.scss, src/scss/_mixins.scss, src/scss/_type-mixins.scss, src/scss/_variables.scss, src/scss/use-cases/_general.scss, src/scss/use-cases/_wrapper.scss, test/scss/_mixins.test.scss, test/typography.test.js
Removes the following mixins in favour of updating the arguments of related
mixins [see the v6 proposal](https://github.com/Financial-Times/o-typography/issues/203):
- oTypographySansBold
- oTypographyDisplayBold
- oTypographySerifBold
- oTypographySerifItalic
- oTypographyBold
- oTypographyItalic
Instead `oTypographySans`, `oTypographyDisplay`, and `oTypographySerif` accept a
`$weight` and `$style` argument. If the given weight or style does not have
a corresponding font in Origami an error is thrown. The `$progressive` parameter
has been moved within an `$opts` map to optionally exclude the sizes of a
fallback font, and in addition a font-family option has been added to exclude
the font family; so these mixins may be used to modify a font size without
repeating the font-family …
=> Remove weight and style mixins.

src/scss/use-cases/_general.scss
o-normalise applies styles to sub and sup tags. These interact with
seperate styles applied by o-typography. This appears to have caused
unusually high/low superscript/subscript elements (confirmed with
the design team).
before
after
This commit corrects the position by overriding default o-normalise
styles. It also sets the size of superscript/subscript elements
using relative units so they work in contexts outside of body copy.
=> Update subscript and superscript size and positioning.

MIGRATION.md, demos/src/demo.js, demos/src/demo.scss, demos/src/line-width.mustache, src/scss/_functions.scss
`oTypographyMaxLineWidth` now returns a relative `ch` rather than
`px` value. The `$scale` and `$font` parameters are redundant and
have been removed.
=> Update `oTypographyMaxLineWidth` to use relative units.

MIGRATION.md, main.scss, src/scss/_brand.scss, src/scss/_type-mixins.scss, src/scss/use-cases/_general.scss, src/scss/use-cases/_headings.scss, src/scss/use-cases/_wrapper.scss
Updates list styles and mixins. Taken from the work in progress
o-editorial-typography (which will be updated to build on these
styles). See https://github.com/Financial-Times/o-editorial-typography/pulls?q=is%3Apr+is%3Aclosed
Updates `oTypographyList`.
Removes `oTypographyListOrdered` and `oTypographyListUnordered`.
Other private Sass has been updated and further brand configuration
which is not needed with o-editorial-typography has been removed.
=> Update list styles and private typography Sass.

MIGRATION.md, main.scss, src/scss/_brand.scss, src/scss/_mixins.scss, src/scss/_type-mixins.scss, src/scss/use-cases/_general.scss, src/scss/use-cases/_headings.scss, src/scss/use-cases/_wrapper.scss, test/scss/_mixins.test.scss
We introduced multiple font scales for specialist titles earlier
in the year, so the result of `oTypographySize` depends on the font.
Instead of passing a font type to `oTypographySize` use
`oTypographySans`, `oTypographySerif`, or `oTypographyDisplay` with
arguments instead. This also includes progressive font loading
styles for the updated size, where `oTypographySize` did not.
=> Remove oTypographySize.

src/scss/use-cases/_general.scss, test/scss/_mixins.test.scss
for browsers which don't support `text-decoration-thickness`:
for browsers which do:
closes https://github.com/Financial-Times/o-typography/issues/188
=> Use text-decoration-thickness where support exists

src/scss/use-cases/_general.scss, test/scss/_mixins.test.scss
With `text-decoration-thickness` support the external icon underline does not extend under the icon. This is actually preferable.
Simon C:
>Fine having the underline not extend - that would actually be preferable - the icon should be on the baseline though
I haven't been able to get rid of the underline when `text-decoration-thickness` is not supported without using a pseudo element, but that would allow the icon to wrap on its own and also we need to after pseudo element for the "opens in a new tab" screen reader notice. 
**So we'll maintain the cull underline when  `text-decoration-thickness` is not supported:** 
**But intentionally not have an underline when `text-decoration-thickness` is supported:**
=> Improve external icon position and size.

README.md, src/scss/use-cases/_general.scss, test/scss/_mixins.test.scss
This is so mixes of o-colors palette colours may be used.
(also document the context option)
=> Allow link themes to be created using colours and colour names.

MIGRATION.md, src/scss/_brand.scss
As part of the major release we have made product headings the
default heading. We did not have time to review their visual
style thoroughly but removed excess heading levels 7 and 8.
This commit brings the style of the headings closer to the master
brands current style as apposed to the current internal brand
style.
=> Bring master brand product headings closer to the current style.

demos/src/lists.mustache, src/scss/use-cases/_general.scss
Fix list marker position with support for list block children.
It's a little tricky to get right dynamically without a line-height unit.
parent type: georgia, 18px, 28px line-height
parent type: metric, 20px, 18px line-height
parent type: metric, 32px, 32px line-height
=> Fix list marker position

src/scss/_functions.scss, test/scss/_functions.test.scss, test/scss/index.test.scss
The following mixins are used to output font-family:
- oTypographySans
- oTypographySerif
- oTypographyDisplay
However there are some cases where a font family is needed without
the property -- for example to set a CSS variable defined by a 3rd
party frontend component via iframe
=> Add oTypographyGetFontFamily

main.scss, test/scss/_mixins.test.scss
This previously errored:
```scss
@include oTypography($opts: (
'headings': (1)
));
```
>The "headings" option must be a list of heading levels to include e.g. `(1, 2, 3, 4, 5)`.
That's because
```scss
$a: type-of((1)) // number
$a: type-of((1,)) // list
```
https://github.com/Financial-Times/o-typography/issues/241
=> Update the primary mixin to support the output of a single heading.

src/scss/use-cases/_general.scss, test/scss/_mixins.test.scss
Nested calc functions are not supported in IE11.
Relates to: https://github.com/Financial-Times/o-typography/pull/243
=> Remove use of a nested CSS `calc` function.

README.md, bower.json, demos/src/demo.scss, src/scss/_mixins.scss, src/scss/_variables.scss
Adds the option to error if a font variant (family/weight/style)
is used when a font face for that variant has not been included in
the project. By default no error is thrown unless the Sass variable
`$o-typography-error-for-missing-fonts` is set to a string (a
message to include in the error).
This will allow projects like PageKit to remove fonts and inform
dependent projects what to do with a custom error message.
We may want to make an error the default behaviour in a future major
version of o-typography.
Relates to: https://github.com/Financial-Times/o-typography/issues/249
=> Error when font not included

test/origami.test.js, test/typography.test.js
Stop using the magic imports for proclaim and sinon and pull them from the global because that's where Karma has added them. This is required for obt v10 to be released.
=> Stop using magic webpack imports

README.md
There are good reasons to remove our custom progressive font
loading, but also things to do/trade offs if we were to decide to
remove it. Add a link from the README which provides that
information.
Prompted by this question:
https://financialtimes.slack.com/archives/C02FU5ARJ/p1587634959151800
=> Link to issue on why to keep custom progressive font loading

package.json
[the npm section of the component spec](https://origami.ft.com/spec/v1/components/#npm) says that components' `package.json`s **must not** include the `dependencies` property
However, this component does contain npm dependencies:
https://github.com/Financial-Times/o-typography/blob/master/package.json#L3-L6
One of these dependencies is also listed in the bower.json:
https://github.com/Financial-Times/o-typography/blob/master/bower.json#L14
the other dependency is available in bower... but also it appears not to be used?:
https://github.com/Financial-Times/o-typography/pull/115
i think it was missed in PR #115
=> remove npm dependencies, which are a deviation from the spec :o

MIGRATION.md
I think I got this right, but AFAICT the class suggested to migrate to doesn't exist.
=> Fixes editorial typography typo in MIGRATION.md

README.md, src/scss/_brand.scss
- blockquotes are not in the latest major of o-typography (see o-quote instead)
- the responsive heading options were not documented
=> Improve `oTypographyCustomize` documentation.

main.js, test/origami.test.js, test/typography.test.js
relative imports require the full path including the extension because browsers use the import name to make a network request and they do not implicitly add a .js file extension if one is missing
=> add extension to relative imports to make the code work directly in a browser

bower.json
dotcom-page-kit preloads font files using JS. It needs to match
the font files used by o-typography, which we can achieve by
requiring the most recent o-fonts version or later.
https://github.com/Financial-Times/dotcom-page-kit/pull/826
In the future o-fonts should provide a JS api to get the
font url used for preloading. Perhaps in design token form
=> Require the latest o-fonts release
